pipeline {
	agent any 
	
	stages {
	    stage('Checkout') {
	        steps {
			checkout scm			       
		      }}
		stage('Build') {
	           steps {
			  sh '/home/pratik/Documents/Devops-Software/apache-maven-3.9.6/bin/mvn install'
	                 }}
		stage('Deployment'){
		   steps {
		sh 'cp target/PIPELINE.war /home/pratik/Documents/Devops-Software/apache-tomcat-9.0.88/webapps'
			}}	
}}
